@hostname = localhost:5000
@protocol = http
@baseURL = {{protocol}}://{{hostname}}

# prouduct apis

GET {{baseURL}}/products HTTP/1.1
###
POST {{baseURL}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "sprite",
    "description": "changed description"
}
###
PATCH {{baseURL}}/products/1 HTTP/1.1
Content-Type: application/json

{
    "name": "coke",
    "description": "changed description"
}

###
DELETE {{baseURL}}/products/4 HTTP/1.1
Content-Type: application/json


# order apis

###
GET {{baseURL}}/orders HTTP/1.1
###
POST {{baseURL}}/orders HTTP/1.1
Content-Type: application/json

###
PATCH {{baseURL}}/orders/1 HTTP/1.1
Content-Type: application/json

{
    "isDelivered": false
}

###
DELETE {{baseURL}}/orders/1 HTTP/1.1
Content-Type: application/json

# shop apis

###
GET {{baseURL}}/shops HTTP/1.1
###
POST {{baseURL}}/shops HTTP/1.1
Content-Type: application/json

{
    "name": "firoz"
}

###
PATCH {{baseURL}}/shops/2 HTTP/1.1
Content-Type: application/json

{
    "name": "ershad vai",
    "location": "kawla, moddhopara"
}

###
DELETE {{baseURL}}/shops/1 HTTP/1.1
Content-Type: application/json

###
GET {{baseURL}}/shops/1/order HTTP/1.1
###
POST {{baseURL}}/shops/1/order HTTP/1.1
Content-Type: application/json

{
    "comment": "wliefoiwf",
    "products": [
        {
            "id": 1,
            "unitPrice": 550,
            "quantity": 12
        },
        {
            "id": 2,
            "unitPrice": 630,
            "quantity": 12
        }
    ]
}

###
PATCH {{baseURL}}/shops/1/order/1 HTTP/1.1
Content-Type: application/json

{
    "comment": "wliefoiwf",
    "products": [
        {
            "id": 1,
            "unitPrice": 11,
            "quantity": 12
        },
        {
            "id": 2,
            "unitPrice": 22,
            "quantity": 10
        }
    ]
}


###
POST {{baseURL}}/shops/1/order/1/delivered HTTP/1.1
Content-Type: application/json

###
POST {{baseURL}}/users/register HTTP/1.1
Content-Type: application/json

{
    "email": "arman@gmail.com",
    "password": "test",
    "firstName": "arman",
    "lastName": "ahmed"
}

###
POST {{baseURL}}/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "arman@gmail.com",
    "password": "test"
}

###
GET {{baseURL}}/transactions HTTP/1.1